### ISSUE TITLE
can help me config server security , thanks 

### ISSUE THREAD

**Issue by keryhu** [kamkie/intellijSettings#1]
First , thanks last help !
I want to config spring cloud server security like you --https://github.com/keryhu/micro-service-example/blob/master/service-config/src/main/resources/application.yml

 ```
serviceUrl:
      defaultZone: https://user:${eureka.password}@localhost:8899/eureka/
```

when i try , meet some errors , i push this --http://stackoverflow.com/questions/35167947/how-to-implement-spring-cloud-config-server-security-with-docker

can help me ? thanks !

**Comment by kamkie** [comment]
i think you opened this issue in wrong project
my answer is on SO

**Comment by keryhu** [comment]
sorry,
i know ,thanks  your answer . your are friendly .

i try your suggests .
